# http://travis-ci.org/#!/mitxlti/pylti
language: python
python:
    - 2.7
install:
    - python setup.py install --quiet
    - pip install coveralls
script:
    - python setup.py test --coverage --pep8 --flakes
after_success: coveralls

